### ISSUE TITLE
Error when decoding bytes dlhn produced

### ISSUE THREAD

**Issue by udoprog** [otake84/dlhn#14]
Hi!

Included in musli is a deterministic fuzzer, one thing it does is generate random datastructures and then tries to pipe them through a serialize / deserialize phase.

I've had to disable dlhn now because it produces bytes that it fails to deserialize:

```
> cargo run -p musli-tests --bin fuzz --features dlhn -- large
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/fuzz large`
serde_dlhn/large: .E
0: error during decode: Read error
0: failing structure written to target/serde_dlhn_error.bin
 734.045µs
```

[This is the structure being serialized](https://github.com/udoprog/musli/blob/main/crates/musli-tests/src/models.rs#L261).

You can [check out the project yourself](https://github.com/udoprog/musli) and give the above command a run and you should be able to troubleshoot this yourself.

**Comment by otake84** [comment]
Thanks for the comment, @udoprog ,

Sorry for the late reply. I'm currently dealing with some personal issues, making it hard to address this problem right away. I plan to tackle it as soon as things settle down on my end.

I appreciate your understanding!

**Comment by otake84** [comment]
I apologize for the delay in addressing this issue. I have just released the updated version. Thank you, @udoprog, for your support.
